### ISSUE TITLE
GitHub Issue: Create Reusable Action for AWS Self-Hosted Runner Management

### ISSUE THREAD

**Issue by yonch** [unvariance/collector#126]
## Background

We currently have duplicated code across multiple GitHub Actions workflows for managing AWS self-hosted runners. **This repetition makes maintenance difficult and increases the risk of inconsistencies between workflows** when changes are needed.

Looking at our current implementation in `test-kernel-module.yaml`, we see the same pattern repeated:
- A job that starts an EC2 runner
- Workflow jobs that use this runner
- A final job that stops the EC2 runner

## Proposal

Create a reusable GitHub Action (composite action) that encapsulates the runner provisioning and cleanup logic. This would allow us to:

1. Reduce code duplication across workflows
2. Maintain configuration in a single location
3. More easily update and improve our runner management
4. Standardize inputs and outputs across workflows

### Functionality
- Create a composite action that handles both starting and stopping EC2 runners
- Support all current configuration options from our existing workflows
- Maintain compatibility with our current workflow patterns
- Provide clear documentation for usage

### Inputs
The action should provide sensible defaults while allowing overrides when needed:

All inputs should be optional with sensible defaults:
- `instance-type`: EC2 instance type (default: 'm7i.xlarge')
- `market-type`: Market type (default: 'spot')
- `github-token`: Token for GitHub API access (default: ${{ secrets.REPO_ADMIN_TOKEN }})
- `aws-role-arn`: ARN of the AWS role to assume (default: ${{ secrets.AWS_ROLE_ARN }})
- `aws-region`: AWS region to create the instance in (default: ${{ secrets.AWS_REGION }})
- `subnet-id`: AWS subnet ID for the instance (default: ${{ secrets.AWS_SUBNET_ID }})
- `security-group-id`: AWS security group ID for the instance (default: ${{ secrets.AWS_SECURITY_GROUP_ID }})
- `aws-image-id`: Custom AMI ID (default: Ubuntu 22.04 LTS AMI for the specified region)
- `aws-resource-tags`: Custom resource tags (default: repository, workflow, and run information)

### Outputs
The action should provide these outputs:
- `runner-label`: The label of the created runner (for use in `runs-on`)
- `ec2-instance-id`: The ID of the created EC2 instance

### Implementation
- Create a composite action in `.github/actions/aws-runner/`
- Split into logical components:
  - `action.yml`: Main action definition
  - `cleanup.yml`: Action for stopping the runner
- Use GitHub's composite actions feature to orchestrate the process
- Maintain backward compatibility with existing workflows

### Usage Example
Workflows should be able to use the action with minimal configuration:

```yaml
jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-runner.outputs.runner-label }}
      ec2-instance-id: ${{ steps.start-runner.outputs.ec2-instance-id }}
    steps:
      - name: Start AWS Runner
        id: start-runner
        uses: ./.github/actions/aws-runner
        with:
          instance-type: 'm7i.xlarge'
          # All other parameters use defaults from repository secrets

  test-job:
    needs: setup-runner
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    steps:
      # Test steps here

  cleanup-runner:
    if: always()
    needs: [setup-runner, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Stop AWS Runner
        uses: ./.github/actions/aws-runner/cleanup
        with:
          runner-label: ${{ needs.setup-runner.outputs.runner-label }}
          ec2-instance-id: ${{ needs.setup-runner.outputs.ec2-instance-id }}
          # Uses default github-token from repository secrets
```

If specific overrides are needed:

```yaml
jobs:
  setup-custom-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-runner.outputs.runner-label }}
      ec2-instance-id: ${{ steps.start-runner.outputs.ec2-instance-id }}
    steps:
      - name: Start Custom AWS Runner
        id: start-runner
        uses: ./.github/actions/aws-runner
        with:
          instance-type: 'm7i.metal-24xl'
          market-type: 'on-demand'
          aws-image-id: 'ami-0123456789abcdef0'
          aws-region: 'us-west-2'
          # Other parameters can be overridden as needed
```

## Implementation Details

The implementation will involve creating a composite action that wraps the existing `machulav/ec2-github-runner` action, but with our standardized configuration. 

The main steps involve:

1. **Create a new action structure** in `.github/actions/aws-runner/`
   - Main `action.yml` file defining inputs, outputs, and steps
   - A cleanup component for stopping the runner

2. **Extract common configuration** from existing workflows:
   - Default AMI IDs
   - Standard tags
   - Reuse the existing `machulav/ec2-github-runner` action
   - Directly use repository secrets rather than passing them as inputs

3. **Update existing workflows** to use the new reusable action

## Benefits

This refactoring will:

1. **Reduce code duplication** - we'll have a single reference implementation
2. **Simplify workflow files** - less boilerplate in each workflow
3. **Make updates easier** - changes to runner configuration only happen in one place
4. **Improve consistency** - all workflows will use the same runner setup

## Related Work

- Current AWS runner configuration in our workflows
- GitHub's documentation on [[composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)

## References

1. Current implementation in `test-kernel-module.yaml`
2. [[GitHub's documentation on reusable actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions)](https://docs.github.com/en/actions/creating-actions/about-custom-actions)
3. [[machulav/ec2-github-runner](https://github.com/machulav/ec2-github-runner)](https://github.com/machulav/ec2-github-runner) action
