### ISSUE TITLE
Implement helm chart

### ISSUE THREAD

**Issue by yonch** [unvariance/collector#136]
## Objective

Create a Kubernetes Helm chart for the Memory Collector that follows best practices and provides a standardized, user-friendly deployment experience.

## Background

The Memory Collector is an eBPF-based tool that collects memory subsystem metrics and writes them to Parquet files in object storage (initially S3). We need a Helm chart that makes it easy to deploy in different Kubernetes environments while minimizing security privilege requirements.

### Chart Structure

Implement a standard Helm chart structure:
```
charts/
└── collector/
    ├── Chart.yaml
    ├── values.yaml
    ├── templates/
    │   ├── _helpers.tpl
    │   ├── daemonset.yaml
    │   ├── configmap.yaml
    │   ├── serviceaccount.yaml
    │   ├── clusterrole.yaml
    │   ├── clusterrolebinding.yaml
    │   ├── secret.yaml (optional, for S3 credentials)
    │   └── NOTES.txt
    └── README.md
```

### Deployment Mode

- Primary deployment mode: **DaemonSet** to run on every eligible node
- Support two modes of deployment:
  1. Run on all nodes (default) -- deploy as DaemonSet
  2. Run on a limited subset of nodes (sampling mode) -- deploy as Deployment or StatefulSet with the requested number of replicas (make sure any node can only have one replica)
- In either mode, user could select specific nodes, tolerations, etc.

### Parameters Organization

Organize values in a logical hierarchy in `values.yaml`:

```yaml
# General configuration
nameOverride: ""
fullnameOverride: ""

# Image configuration
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  # Mode: all, sample, or select
  mode: "all"
  # When in sample mode, how many nodes to run on
  sampleSize: 5

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Security context and capabilities
securityContext:
  # Start with minimal privileges, avoid privileged: true
  privileged: false
  capabilities:
    add: []  # Will be populated based on testing

# Storage configuration
storage:
  type: "s3"  # Only s3 supported initially
  prefix: "path/and/object-prefix-"
  
  # S3-specific configuration
  s3:
    bucket: ""
    region: ""
    endpoint: ""  # For non-AWS S3-compatible storage
    pathStyle: false
    
    # Authentication methods
    auth:
      method: "iam"  # Options: "iam", "secret"
      # For "secret" method
      accessKey: ""
      secretKey: ""
      existingSecret: ""  # Reference existing secret
      existingSecretKeyMapping:
        accessKey: "access-key"
        secretKey: "secret-key"

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

### Security Configurations

1. **Minimize privileges:**
   - Start with non-privileged mode
   - Identify minimum required capabilities through testing
   - Document all required capabilities with rationale
   - Avoid volume mounts initially, then add only what's necessary
   
2. **Support for Pod Security Standards:**
   - Document PSA compatibility
   - Provide guidance on required exemptions
   - Test with restrictive PSA configurations

### Node Selection

Implement options for node selection:

1. **All mode (default):**
   - Run on all nodes in the cluster

2. **Sample mode:**
   - Run on a limited number of nodes (e.g., 5)
   - Use appropriate scheduling configuration to distribute evenly
   
3. **Select mode:**
   - Run on specific nodes based on labels
   - Allow users to specify node selection criteria

### Storage Configuration

Initial support for S3 with the following configurations:

1. **Authentication options:**
   - IAM roles for service accounts (preferred)
   - Static credentials from values
   - Existing secret reference

2. **S3 compatibility:**
   - Support AWS S3
   - Support S3-compatible storage (via endpoint and path-style addressing)

### Testing

1. **Basic functionality:**
   - Verify chart installation on a standard K3S cluster
   - Validate all parameters work as expected
   
2. **Security testing:**
   - Test with Pod Security Standards enabled
   - Identify minimum required privileges
   - Verify functionality with restricted privileges
   
3. **Configuration testing:**
   - Test all node selection modes
   - Test all authentication methods for S3

## Acceptance Criteria

1. Chart installs successfully on a standard K3S cluster
2. Chart works with Pod Security Standards enforced
3. All deployment modes function as expected
4. S3 storage configuration works with all authentication methods
5. Documentation clearly explains all parameters
6. NOTES.txt provides useful post-installation information
7. All configuration options are tested

## Implementation Notes

1. Start with minimal privileges and add only what is required
2. Use helper functions to keep templates DRY
3. Follow Helm best practices for templating
4. Use conditional logic to support different deployment scenarios
5. Document clearly in README.md and NOTES.txt

## Future Enhancements

These are out of scope for the initial implementation:

1. Support for Google Cloud Storage
2. Support for Azure Blob Storage
3. Support for other output formats beyond Parquet
